spring:
  application:
    name: payment
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
      properties:
        retry.backoff.ms: 200
        delivery.timeout.ms: 60000
server:
  port: 8082

kafka:
  topics:
    new-orders-topic: new_orders
    payed-orders-topic: payed_orders
    concurrency: 3