spring:
  application:
    name: notifications
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notifications
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 8084

kafka:
  topics:
    sent-orders-topic: sent_orders
    concurrency: 3